// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXAYRbT4No0rZ2COibkzsarPoQFLfDQi4',
    appId: '1:511869146050:web:134ff0c36cd9abe584bc5b',
    messagingSenderId: '511869146050',
    projectId: 'ecoloop-14a94',
    authDomain: 'ecoloop-14a94.firebaseapp.com',
    storageBucket: 'ecoloop-14a94.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWPVafXRYYBMVqIrgDXj69n2h9Dy1dWOg',
    appId: '1:511869146050:android:5c701b26fcac4bb784bc5b',
    messagingSenderId: '511869146050',
    projectId: 'ecoloop-14a94',
    storageBucket: 'ecoloop-14a94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwVPytyhUzazwvqvOzuaidaCQjv36ab8k',
    appId: '1:511869146050:ios:5645d6582335e69484bc5b',
    messagingSenderId: '511869146050',
    projectId: 'ecoloop-14a94',
    storageBucket: 'ecoloop-14a94.firebasestorage.app',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwVPytyhUzazwvqvOzuaidaCQjv36ab8k',
    appId: '1:511869146050:ios:5645d6582335e69484bc5b',
    messagingSenderId: '511869146050',
    projectId: 'ecoloop-14a94',
    storageBucket: 'ecoloop-14a94.firebasestorage.app',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXAYRbT4No0rZ2COibkzsarPoQFLfDQi4',
    appId: '1:511869146050:web:ef85668c413db7cc84bc5b',
    messagingSenderId: '511869146050',
    projectId: 'ecoloop-14a94',
    authDomain: 'ecoloop-14a94.firebaseapp.com',
    storageBucket: 'ecoloop-14a94.firebasestorage.app',
  );
}
